### ISSUE TITLE
json decoding error related to jenkins module when trying to use the ci-cd module

### ISSUE THREAD

**Issue by scott2b** [cn-terraform/terraform-aws-ci-cd-system#3]
I get the following error for this module:

│ Error: ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal string into Go struct field MountPoint.MountPoints.ReadOnly of type bool
│
│   with module.ci-cd-system.module.jenkins.module.td.aws_ecs_task_definition.td,
│   on .terraform/modules/ci-cd-system.jenkins.td/main.tf line 81, in resource "aws_ecs_task_definition" "td":
│   81:   container_definitions = "[${module.container_definition.json_map_encoded}]"
│

**Comment by redondosole** [comment]
This seems to be an issue on terraform 0.15+
I was able to get to work on 0.14 with a minor modification.

**Comment by jnonino** [comment]
Hi, how are you? Which is the modification you need to do? I tested with Terraform 1.0.10 and it works.

**Comment by jnonino** [comment]
Hi @redondosole , do you have any updates on this?

**Comment by redondosole** [comment]
Im trying to see what i changed, I got this working making changes to my .terraform files.

I just noticed that i have version 50, and now theres v 58 of modules, maybe if you start a clean env it works now?

**Comment by jnonino** [comment]
Hi, thanks for your answer, if you can test the new version or find out what you needed to change to make work it will be very helpful to improve the module and fix anything that could be happening.

**Comment by jnonino** [comment]
Hi, I'm closing this issue as it has been a long time without new reports. If you find this is still happening, please reopen.
